
name: branch-protection.yml

on:
  push:
    branches: [main]

jobs:
  enforce-branch-rules:
    runs-on: ubuntu-latest
    steps:
      - name: Check for code changes
        run: git diff --quiet HEAD^ HEAD
        shell: bash
      - name: Check for code coverage report
        uses: actions/download-artifact@v2
        with:
          name: code-coverage-report
          path: coverage-report
        if: ${{ success() }}
      - name: Verify code linting and unit tests
        uses: actions/download-artifact@v2
        with:
          name: linting-and-unit-tests
          path: linting-and-unit-tests
        if: ${{ success() }}
      - name: Fail if requirements not met
        run: exit 1
        if: ${{ failure() }}