

name: branch-protection.yml
on:
  push:
    branches: [main]
jobs:
  enforce-branch-rules:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      - name: Check for code changes
        if: ${{ github.event.head_commit.added != '' || github.event.head_commit.modified != '' }}
        run: echo "Code changes detected."
      - name: Enforce code coverage report
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Verify code linting and unit tests
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Complete job
        run: echo "Job complete."