

# branch-protection.yml
name: "Branch Protection Workflow"

on:
  push:
    branches:
      - main

jobs:
  enforce-branch-rules:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [20.x]
        java-version: [maven]
      
    steps:
      - name: Check for code changes
        uses: actions/github-script@v3
        with:
          script: |
            if (github.event.commits.length > 0) {
              console.log("Code changes detected!");
            } else {
              console.log("No code changes found.");
            }
      
      - name: Enforce code coverage report
        run: npm run coverage
      
      - name: Verify code linting and unit tests
        run: npm run lint && npm test
      
      - name: Complete job
        run: echo "Job completed successfully!"