

name: branch-protection.yml
on:
  push:
    branches:
      - main
jobs:
  enforce-branch-rules:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Check for code changes
        run: git diff --exit-code
      - name: Enforce code coverage report
        run: npm run coverage
      - name: Verify code linting and unit tests
        run: npm run lint && npm test
    if: success()
    steps:
      - name: Set up job
        run: echo "Setting up job"
      - name: Check for code changes
        run: git diff --exit-code
      - name: Enforce code coverage report
        run: npm run coverage
      - name: Verify code linting and unit tests
        run: npm run lint && npm test
      - name: Complete job
        run: echo "Job completed"