


name: branch-protection.yml

on:
  push:
    branches: [main]

jobs:
  enforce-branch-rules:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      - name: Check for code changes
        run: git diff --exit-code
      - name: Enforce code coverage report
        if: ${{ steps.check.outputs.has_changes == 'true' }}
        run: npm run coverage
      - name: Verify code linting and unit tests
        if: ${{ steps.check.outputs.has_changes == 'true' }}
        run: npm run lint && npm run test
      - name: Complete job
        if: ${{ steps.check.outputs.has_changes == 'true' }}
        run: echo "Job completed successfully."