
name: Python
version: 1.21.0
description: Fundamental package for scientific computing with Python

name: pandas
version: 1.3.3
description: Powerful data structures for data analysis, time series, and statistics

name: react
version: 17.0.2
description: A JavaScript library for building user interfaces

name: axios
version: 0.21.1
description: Promise based HTTP client for the browser and node.js

name: tailwindcss
version: 2.2.19
description: A utility-first CSS framework for rapid UI development