

branch-protection.yml:

name: branch-protection

on:
  push:
    branches:
      - main

jobs:
  enforce-branch-rules:
    runs-on: ubuntu-latest
    steps:
      - name: Check for code changes
        uses: actions/github-script@v3
        with:
          script: |
            if (github.event.commits.length === 0) {
              core.setFailed('No code changes were made.');
            }
      - name: Ensure code coverage report is available
        uses: actions/download-artifact@v2
        with:
          name: code-coverage-report
          path: code-coverage-report
      - name: Verify code linting and unit tests
        uses: actions/github-script@v3
        with:
          script: |
            if (github.event.workflow_runs != undefined) {
              for (const run of github.event.workflow_runs) {
                if (run.status !== 'completed' || run.conclusion !== 'success') {
                  core.setFailed('Code linting or unit tests failed in a previous workflow.');
                }
              }
            }
      - name: Fail workflow if requirements are not met
        if: ${{ failure() }}
        run: exit 1