

name: branch-protection.yml

on:
  push:
    branches:
      - main
      
jobs:
  enforce-branch-rules:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      - name: Check for code changes
        run: git diff --name-only ${{ github.event.before }} ${{ github.event.after }}
        id: check-changes
      - name: Enforce code coverage report
        if: steps.check-changes.outputs.codechanges == 'true'
        run: npm run coverage
        id: code-coverage
      - name: Verify code linting and unit tests
        if: steps.check-changes.outputs.codechanges == 'true'
        run: npm run lint && npm run test
        id: code-linting-tests
      - name: Complete job
        if: steps.check-changes.outputs.codechanges == 'true'
        run: echo "Job completed successfully."