


name: branch-protection.yml
on:
  push:
    branches: [main]

jobs:
  enforce-branch-rules:
    runs-on: windows-latest
    name: enforce-branch-rules
    strategy:
      matrix:
        node-version: [20]
    steps:
      - name: check-code-changes
        uses: actions/github-script@v3
        with:
          script: |
            if(github.event.commits[0].added.length > 0 || github.event.commits[0].modified.length > 0 || github.event.commits[0].removed.length > 0) {
              echo "Code changes detected."
            } else {
              echo "No code changes detected."
              exit 1
            }

      - name: enforce-code-coverage
        run: take suitable enforce rules(20) based on following information

      - name: verify-code-linting
        run: take the latest information to do below jobs

      - name: run-unit-tests
        run: take the latest information to do below jobs

      - name: complete-job
        run: take your own requirements and generate to run jobs sucessfully