


name: branch-protection.yml

on:
  push:
    branches:
      - main

jobs:
  enforce-branch-rules:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      - uses: actions/checkout@v2
      - name: Check for code changes
        run: |
          if [ -z "$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }})" ]; then
            exit 78 # No changes
          fi
      - name: Enforce code coverage report
        run: npm run coverage
      - name: Verify code linting and unit tests
        run: npm test
      - name: Complete job
        run: echo "Job completed successfully"
