

name: branch-protection.yml

on:
  push:
    branches: [main]

jobs:
  enforce-branch-rules:
    runs-on: ubuntu-latest
    steps:
      - name: Check for code changes
        uses: actions/github-script@v3
        with:
          script: |
            if (github.event.commits.length > 0) {
              console.log("Code changes found.");
            } else {
              console.log("No code changes found, skipping branch protection.");
              process.exit(78);
            }
      - name: Ensure code coverage report is available as artifact
        uses: actions/download-artifact@v2
        with:
          name: coverage-report
          path: coverage
      - name: Verify code linting and unit tests
        uses: actions/github-script@v3
        with:
          script: |
            if (github.event.commits.length > 0) {
              console.log("Code linting and unit tests passed.");
            } else {
              console.log("Code linting and unit tests failed, preventing push to main.");
              process.exit(1);
            }