

name: deploy-process

on:
  pull_request:
    branches:
      - development

jobs:
  build:
    runs-on: android-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
          default: true
      - name: Install Dependencies
        run: yarn install
      - name: Build Project
        run: ./build-process.sh
      - name: Deploy to Testing Environment
        if: success()
        run: ./deploy-process.sh
      - name: Notify Discord
        if: success()
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.WEBHOOK_ID }}
          webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
          message: Deployment Successful