
name: branch-protection.yml

on:
  push:
    branches:
      - main

jobs:
  enforce-branch-rules:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && contains(github.event.head_commit.modified, 'code changes')
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: code-coverage-report
          path: coverage-report
      - name: Verify linting and unit tests
        run: |
          # verify linting
          # run unit tests
      - name: Fail if requirements not met
        run: exit 1