
# Name: api-docs.yml

on:
  push:
    branches:
      - main

jobs:
  build-docs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm install
      - name: Install API Documentation Tools
        run: npm install -g swagger-jsdoc
      - name: Generate API Documentation
        run: swagger-jsdoc -d docs -o api-docs
      - name: Archive Documentation
        uses: actions/upload-artifact@v2
        with:
          name: API Documentation
          path: api-docs
  deploy-docs:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Deploy Documentation
        run