

name: release-pipeline.yml

on:
  push:
    branches:
      - main

jobs:
  enforce-branch-rules:
    runs-on: macOS-latest
    steps:
      - name: Check for code changes
        run: |
          if [ -n "$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }})" ]; then
            echo "Code changes detected, enforcing requirements"
          else
            echo "No code changes detected"
            exit 1
          fi
        shell: bash

      - name: Ensure code coverage report
        uses: actions/download-artifact@v2
        with:
          name: code-coverage
          path: coverage-report

      - name: Verify code linting and unit tests
        uses: actions/download-artifact@v2
        with:
          name: linting-and-tests
          path: linting-and-tests

      - name: Fail workflow if requirements not met
        run: |
          if [ -f coverage-report/index.html ] && [ -f linting-and-tests/success.txt ]; then
            echo "All requirements met, pushing to main"
          else
            echo "Failed to meet requirements, preventing push to