

name: branch-protection.yml

on:
  push:
    branches: [main]

jobs:
  enforce-branch-rules:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    steps:
      - name: Check for code changes
        run: git diff --quiet || exit 1
      - name: Download code coverage report
        uses: actions/download-artifact@v2
        with:
          name: check-coverage
      - name: Verify code coverage report
        run: |
          if [ ! -f report.xml ]; then
            echo "Missing code coverage report!"
            exit 1
          fi
      - name: Download test results
        uses: actions/download-artifact@v2
        with:
          name: run-tests
      - name: Verify test results
        run: |
          if [ ! -f results.xml ]; then
            echo "Missing test results!"
            exit 1
          fi
      - name: Fail workflow if checks fail
        run: exit 1