
name: branch-protection.yml
on:
  push:
    branches:
      - main
jobs:
  enforce-branch-rules:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Check for code changes
        uses: actions/checkout@v2
      - name: Enforce requirements
        run: |
          if [[ -n "$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }})" ]]; then
            if [ -z "${{ github.event.pull_request.head.repo.clone_url }}" ]; then
              echo "Error: No code coverage report available as artifact. Please generate one from a previous workflow."
              exit 1
            fi
            if [ -n "${{ github.event.head_commit.message }}" ]; then
              echo "Error: Code linting and unit tests did not pass successfully. Please fix any issues and try again."
              exit 1
            fi
          fi