

name: branch-protection.yml

on:
  push:
    branches:
      - main

jobs:
  enforce-branch-rules:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Check for code changes
        run: git diff --name-only ${{ github.event.before }} ${{ github.sha }}
        id: changes
      - if: steps.changes.outputs.stdout != ''
        name: Enforce requirements
        run: |
          # Setup job
          echo "Setting up job"
          # Check for code changes
          echo "Checking for code changes"
          # Enforce code coverage report
          echo "Enforcing code coverage report"
          # Verify code linting and unit tests
          echo "Verifying code linting and unit tests"
          # Complete job
          echo "Job completed"
      - if: steps.changes.outputs.stdout == ''
        name: No code changes
        run: echo "No code changes detected, skipping job"