

name: branch-protection.yml

on:
  push:
    branches:
      - main

jobs:
  enforce-branch-rules:
    runs-on: ubuntu-latest
    steps:
      - name: check for code changes
        if: ${{ github.event.head_commit.added != '' || github.event.head_commit.modified != '' }}
        run: |
          # set up job
          # enforce code coverage report
          # verify code linting and unit tests
          # complete job
          # take your own requirements and generate to run jobs successfully