

name: ci-cd.yml

on:
  push:
    branches: [main]

jobs:
  enforce-branch-rules:
    runs-on: macOS-latest
    steps:
      - name: Check for code changes
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Ensure code coverage report is available
        uses: actions/download-artifact@v2
        with:
          name: code-coverage-report
      - name: Verify code linting and unit tests
        run: npm run lint && npm run test
      - name: Fail if requirements not met
        if: ${{ failure() }}
        run: exit 1 