:
name: performance-tests.yml

on:
  pull_request:
    branches: [performance]

jobs:
  run-benchmarks:
    runs-on: high-performance-machine
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install benchmarking tools
        run: |
          sudo apt-get install apache2-utils
          sudo apt-get install wrk
      - name: Run benchmarks
        run: |
          ab -n 1000 -c 10 http://example.com/
          wrk -t12 -c400 -d30s http://example.com/
      - name: Store results
        uses: actions/upload-artifact@v2
        with:
          name: benchmark-results
          path: results

  generate-report:
    runs-on: any
    steps:
      - name: Generate report
        run: |
          sudo apt-get install grafana
          sudo apt-get install plotly
          # use data visualization tool to create report