


name: branch-protection.yml

on:
  push:
    branches:
      - main

jobs:
  enforce-branch-rules:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: check for code changes
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: main
      - name: enforce code coverage report
        run: |
          # insert code coverage report commands here
      - name: verify code linting and unit tests
        run: |
          # insert linting and unit test commands here
      - name: complete job
        run: |
          # insert any final steps or commands here