
      with:
        dotnet-version: '3.1.0'

steps:
  - uses: actions/checkout@v2
  - name: Cache Nuget
    uses: actions/cache@v1
    with:
      path: ~/.nuget/packages
      key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
      restore-keys: |
        ${{ runner.os }}-nuget-
  - name: Setup .NET
    uses: actions/setup-dotnet@v1
    with:
      dotnet-version: '3.1.0'