

name: branch-protection

on:
  push:
    branches:
      - main

jobs:
  enforce-branch-rules:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    steps:
      - name: Check for code changes
        uses: actions/checkout@v2
      - name: Enforce code coverage report
        run: |
          # insert code coverage commands here
      - name: Verify code linting and unit tests
        run: |
          # insert linting and unit tests commands here
      - name: Complete job
        run: |
          # insert any other necessary commands here