
name: docker-build-and-test.yml

on:
  push:
    branches: [develop]

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: my-app
          tag_with_ref: true
          push: true
      - name: Install dependencies
        run: |
          docker build -t my-app:latest .
  run-integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Docker image
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: my-app
          tag_with_ref: true
      - name: Run integration tests
        run: |
          docker run my-app:latest pytest
      - name: Store test results
        uses: actions/upload-artifact@v2
        with:
