


name: branch-protection.yml

on:
  push:
    branches:
      - main

jobs:
  enforce-branch-rules:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Check for code changes
        run: if [ -n "$GITHUB_EVENT_PATH" ]; then echo "Changes detected"; else echo "No changes detected"; exit 1; fi
      - name: Set up job
        run: npm install
      - name: Enforce code coverage report
        run: npm run coverage
      - name: Verify code linting and unit tests
        run: npm run lint && npm run test
      - name: Complete job
        run: echo "Job completed successfully"