

name: branch-protection.yml

on:
  push:
    branches:
      - main

jobs:
  enforce-branch-rules:
    runs-on: ubuntu-latest

    steps:
      - name: Check for code changes
        uses: actions/checkout@v2

      - name: Enforce code coverage report
        if: ${{ github.event_name == 'push' && github.event.head_commit.modified }}
        run: |
          # insert code coverage command here

      - name: Verify code linting and unit tests
        if: ${{ github.event_name == 'push' && github.event.head_commit.modified }}
        run: |
          # insert linting and unit test commands here

      - name: Complete job
        if: ${{ github.event_name == 'push' && github.event.head_commit.modified }}
        run: |
          # insert any additional commands here to complete the job.