

name: branch-protection.yml

on:
  push:
    branches:
      - main

jobs:
  enforce-branch-rules:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && contains(github.event.head_commit.modified, 'code changes')
    steps:
      - name: setup job
        uses: actions/checkout@v2
      - name: check for code changes
        run: git diff --quiet || exit 1
      - name: enforce code coverage report
        run: npm run test:coverage
      - name: verify code linting and unit tests
        run: npm run lint && npm run test:unit
      - name: complete job
        run: echo "Job completed successfully."