


name: branch-protection
on:
  push:
    branches:
      - main
jobs:
  enforce-branch-rules:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      - name: Check for code changes
        if: github.event_name == 'push'
        run: |
          git diff --name-only ${{ github.base_ref }}...${{ github.head_ref }}
          if [ $? -eq 0 ]; then
            echo "There are code changes"
          else
            echo "There are no code changes"
            exit 1
          fi
      - name: Enforce code coverage report
        run: ./enforce-coverage-report.sh
      - name: Verify code linting and unit tests
        run: ./verify-linting-and-unit-tests.sh
      - name: Complete job
        run: echo "Job completed successfully"