

name: branch-protection.yml
on:
  push:
    branches: 
      - main
jobs:
  enforce-branch-rules:
    runs-on: ubuntu-latest
    steps:
      - name: Check for code changes
        uses: actions/github-script@v3
        with:
          script: |
            if (github.event.commits.length > 0) {
              console.log("Code changes detected.")
            } else {
              console.log("No code changes detected. Skipping job.")
              process.exit(1)
            }
      - name: Check for code coverage report
        uses: actions/download-artifact@v2
        with:
          name: code-coverage-report
          path: coverage/
      - name: Verify code linting and unit tests
        run: yarn test
        continue-on-error: true
      - name: Fail if requirements not met
        run: |
          if [ -d "coverage/" ] && [ ${{ job.status }} == "success" ]; then
            echo "All requirements met."
          else
            echo "Requirements not met. Failing workflow."
            exit 1
          fi