

api-docs.yml:

name: API Docs Workflow

on:
  push:
    branches: [main]

jobs:
  build-docs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install API documentation generation tools
        run: npm install -g swagger # or jsdoc
      - name: Generate API documentation
        run: swagger # or jsdoc
      - name: Archive documentation
        uses: actions/upload-artifact@v2
        with:
          name: API Documentation
          path: /docs
  deploy-docs:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - name: Download API Documentation artifact
        uses: actions/download-artifact@v2
        with:
          name: API Documentation
      - name: Deploy documentation
        run: # steps