

name: branch-protection.yml

on:
  push:
    branches:
      - main

jobs:
  enforce-branch-rules:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [20]
        java-version: [maven]
    steps:
      - name: Check for code changes
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        run: git diff --name-only ${{ github.base_ref }}..${{ github.head_ref }}
      - name: Enforce code coverage report
        if: ${{ steps.check_changes.outputs.changed == 'true' }}
        run: npm run coverage
      - name: Verify code linting and unit tests
        if: ${{ steps.check_changes.outputs.changed == 'true' }}
        run: npm run lint && npm run test
      - name: Complete job
        if: ${{ always() }}
        run: echo "Job completed successfully."