

name: branch-protection.yml

on:
  push:
    branches:
      - main

jobs:
  enforce-branch-rules:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Check for code changes
        run: git diff --quiet || echo "Code changes detected"
      - name: Download coverage report
        uses: actions/download-artifact@v2
        with:
          name: code-coverage
          path: coverage/
      - name: Verify linting and unit tests
        run: |
          # Run linting and unit tests
          # If successful, set variable to true
          # Otherwise, set variable to false
      - name: Fail if requirements not met
        if: steps.verify.outputs.success == 'false'
        run: exit 1 