


name: branch-protection.yml
on:
  push:
    branches:
      - main

jobs:
  enforce-branch-rules:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      - name: Check for code changes
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Enforce code coverage report
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: coverage/
      - name: Verify code linting and unit tests
        run: |
          npm install
          npm run lint
          npm test
      - name: Complete job
        run: echo "Job completed successfully."