
name: api-docs.yml

on:
  push:
    branches: [main]
    
jobs:
  build-docs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: Install API documentation generation tools
        run: npm install --save-dev swagger jsdoc
        
      - name: Generate API documentation
        run: npm run generate-docs
        
      - name: Archive documentation folder
        uses: actions/upload-artifact@v2
        with:
          name: docs
          path: docs
          
  deploy-docs:
    runs-on: ${{ github.event.repository.owner.login }}/any
    steps:
      - name: Deploy API documentation
        run: npm run deploy-docs
