

name: branch-protection.yml

on:
  push:
    branches: [main]

jobs:
  enforce-branch-rules:
    runs-on: windows-latest
    steps:
      - name: Update Node.js to version 20
        uses: actions/setup-node@v2
        with:
          node-version: 20
      - name: Check for code changes
        run: git diff --quiet || echo "Code changes detected."
      - name: Enforce code coverage report
        run: npm run coverage
      - name: Verify code linting and unit tests
        run: npm run lint && npm run test
      - name: Complete job
        run: echo "Job completed successfully."