


name: branch-protection.yml

on:
  push:
    branches: 
      - main

jobs:
  enforce-branch-rules:
    runs-on: ubuntu-latest
    steps:
    - name: set up job
      if: github.event_name == 'push'
      run: echo "Running job"
    - name: check for code changes
      if: ${{ github.event.commits }}
      run: echo "Checking for code changes"
    - name: enforce code coverage report
      if: ${{ github.event.commits }}
      run: echo "Enforcing code coverage report"
    - name: verify code linting and unit tests
      if: ${{ github.event.commits }}
      run: echo "Verifying code linting and unit tests"
    - name: complete job
      if: ${{ github.event.commits }}
      run: echo "Job completed"