

name: branch-protection

on:
  push:
    branches: [main]

jobs:
  enforce-branch-rules:
    runs-on: ubuntu-latest
    steps:
      - name: Check for code changes
        run: git diff --name-only <old_commit> <new_commit> > changed_files.txt
      - name: Download code coverage report
        uses: actions/download-artifact@v2
        with:
          name: code-coverage-report
          path: code-coverage-report
      - name: Verify linting and unit tests
        run: # verify linting and unit tests from previous workflow
      - name: Fail if requirements not met
        if: steps.code-coverage-report.outputs.code-coverage < 100
        run: exit 1