


name: branch-protection.yml

on:
  push:
    branches: [main]

jobs:
  enforce-branch-rules:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Check for code changes
        run: git diff --quiet || exit 1
      - name: Set up job
        run: |
          # insert commands to set up job
      - name: Enforce code coverage report
        run: |
          # insert commands to enforce code coverage report
      - name: Verify code linting and unit tests
        run: |
          # insert commands to verify code linting and unit tests
      - name: Complete job
        run: |
          # insert commands to complete job