


name: release-pipeline

on:
  pull_request:
    branches:
      - develop

jobs:
  build:
    name: Build and Deploy
    runs-on: macOS-latest
    steps:
      - name: Install Node.js version 14
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Set Node.js as default
        run: sudo ln -sf /usr/local/bin/node /usr/local/bin/nodejs
      - name: Install dependencies
        run: yarn install
      - name: Build project
        run: ./build.sh
      - name: Deploy to testing environment
        run: ./deploy.sh
        if: success()
      - name: Notify Microsoft Teams
        uses: microsoft/teams-notification@v1
        with:
          webhook_url: ${{ secrets.MICROSOFT_TEAMS_WEBHOOK }}
          message: "Project successfully deployed to testing environment!"