

name: branch-protection.yml

on:
  push:
    branches: [main]

jobs:
  enforce-branch-rules:
    runs-on: ubuntu-latest
    steps:
      - name: Check for code changes
        uses: actions/checkout@v2
      - name: Enforce code coverage report
        if: github.event_name == 'push'
        run: |
          # insert code here to generate code coverage report
      - name: Verify code linting and unit tests
        if: github.event_name == 'push'
        run: |
          # insert code here to verify code linting and run unit tests
      - name: Complete job
        if: github.event_name == 'push' && success()
        run: |
          # insert code here to complete job
      - name: Take own requirements
        if: github.event_name == 'push'
        run: |
          # insert code here to take own requirements
          # insert code here to run jobs successfully