
name: api-docs.yml
on: 
  push:
    branches: 
      - main

jobs:
  build-docs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: Generate API documentation
        run: npm run generate-docs
      - name: Archive documentation
        uses: actions/upload-artifact@v2
        with:
          name: generated-docs
          path: docs/

  deploy-docs:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: generated-docs
          path: docs/
      - name: Deploy to GitHub Pages
        run: |
          # Commands to deploy to GitHub Pages
          # This