
name: branch-protection.yml

on:
  push:
    branches: [main]

jobs:
  enforce-branch-rules:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && contains(github.event.head_commit.message, 'code changes')
    steps:
      - name: Setup job
        uses: actions/checkout@v2
      - name: Check for code changes
        run: git diff --quiet || exit 1
      - name: Enforce code coverage report
        run: npm run coverage
      - name: Verify code linting and unit tests
        run: npm run lint && npm run test
      - name: Complete job
        run: echo "Job completed successfully."