

name: branch-protection.yml

on:
  push:
    branches:
      - main

jobs:
  enforce-branch-rules:
    runs-on: ubuntu-latest
    steps:
      - name: Check for code changes
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Check code coverage
        uses: actions/download-artifact@v2
        with:
          name: code-coverage
      - name: Verify code linting and unit tests
        uses: actions/download-artifact@v2
        with:
          name: code-linting-and-tests
      - name: Fail if requirements not met
        run: |
          if [[ -z "${{ steps.code-coverage.outputs.artifact }}" || -z "${{ steps.code-linting-and-tests.outputs.artifact }}" ]]; then
            exit 1
          fi