

name: branch-protection.yml

on:
  push:
    branches: [main]

jobs:
  enforce-branch-rules:
    runs-on: ubuntu-latest
    steps:
      - name: Check for code changes
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        run: git diff --name-only HEAD HEAD~1
      - name: Enforce code coverage report
        if: ${{ steps.check_changes.outputs.changed == 'true' }}
        run: npm run coverage
      - name: Verify code linting and unit tests
        if: ${{ steps.check_changes.outputs.changed == 'true' }}
        run: npm run lint && npm run test
      - name: Complete job
        if: ${{ steps.check_changes.outputs.changed == 'true' }}
        run: echo "Job completed successfully."