

name: branch-protection.yml

on: 
  push:
    branches: [main]

jobs: 
  enforce-branch-rules:
    runs-on: ubuntu-latest
    steps:
      - name: Check for code changes
        uses: actions/github-script@v3
        with:
          script: |
            if (github.context.payload.commits[0].added.length > 0 || github.context.payload.commits[0].modified.length > 0) {
              return true;
            } else {
              return false;
            }
      - name: Check code coverage report
        if: steps.check_changes.outputs.result == 'true'
        uses: actions/download-artifact@v2
        with:
          name: code-coverage-report
      - name: Check code linting and unit tests
        if: steps.check_changes.outputs.result == 'true'
        uses: actions/download-artifact@v2
        with:
          name: code-linting-and-unit-tests
      - name: Fail workflow if requirements not met
        if: steps.check_changes.outputs.result == 'true' && (steps.code-coverage-report.outputs.result == 'false' || steps.code-linting-and-unit-tests.outputs.result == 'false')
