

name: branch-protection.yml

on:
  push:
    branches:
      - main

jobs:
  enforce-branch-rules:
    runs-on: ubuntu-latest
    steps:
      - name: Check for code changes
        id: check-changes
        uses: actions/github-script@v3
        with:
          script: |
            const commits = github.event.commits
            const files = commits[commits.length - 1].added.concat(commits[commits.length - 1].modified)
            core.setOutput('changes', files.length)

      - name: Enforce code coverage report
        if: steps.check-changes.outputs.changes > 0
        run: <insert code coverage command here>

      - name: Verify code linting and unit tests
        if: steps.check-changes.outputs.changes > 0
        run: <insert linting and unit test commands here>

      - name: Complete job
        run: <insert completion command here>