
name: branch-protection.yml

on:
  push:
    branches:
      - main

jobs:
  enforce-branch-rules:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    steps:
      - name: Check for code changes
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Run code coverage report
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage
          path: <path/to/report>
      - name: Verify code linting and unit tests
        run: <command to run linting and tests>
      - name: Fail workflow if requirements not met
        run: exit 1