

name: branch-protection.yml

on:
  push:
    branches: [main]

jobs:
  enforce-branch-rules:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: check-for-changes
        uses: actions/checkout@v2
      - name: setup-job
        run: <insert setup job command here>
      - name: check-code-changes
        run: <insert code change check command here>
      - name: enforce-code-coverage
        run: <insert code coverage enforcement command here>
      - name: verify-linting-unit-tests
        run: <insert linting and unit test verification command here>
      - name: complete-job
        run: <insert job completion command here>