

name: branch-protection.yml

on:
  push:
    branches: [main]

jobs:
  enforce-branch-rules:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && github.event.ref == 'refs/heads/main' }}
    steps:
      - name: Check for code changes
        run: git diff --name-only ${{ github.event.before }} ${{ github.event.after }} > changed_files.txt
      - name: Enforce requirements
        if: ${{ steps.code_changes.outputs.has_changes == 'true' }}
        run: |
          gradle build
          gradle test
          gradle jacocoTestReport
        - name: Upload code coverage report
          uses: actions/upload-artifact@v2
          with:
            name: code-coverage-report
            path: ${{ github.workspace }}/build/reports/jacoco/test/html/index.html
      - name: Verify linting and unit tests
        if: ${{ steps.code_changes.outputs.has_changes == 'true' }}
        run: |
          gradle lint
          gradle test
      - name: Fail workflow if requirements are not met
        if: ${{ steps.code_changes.outputs.has