

name: branch-protection.yml
on:
  push:
    branches:
      - main
jobs:
  enforce-branch-rules:
    runs-on: ubuntu-latest
    steps:
      - name: Check for code changes
        uses: actions/checkout@v2
      - name: Setup job
        run: npm install -g node@16
      - name: Enforce code coverage report
        if: github.event_name == 'push' && github.event.head_commit.modified_files > 0
        run: npm run coverage-report
      - name: Verify code linting and unit tests
        if: github.event_name == 'push' && github.event.head_commit.modified_files > 0
        run: npm run lint && npm run unit-tests
      - name: Complete job
        if: github.event_name == 'push' && github.event.head_commit.modified_files > 0
        run: echo "Job completed successfully."