

name: branch-protection.yml

on:
  push:
    branches: [main]

jobs:
  enforce-branch-rules:
    runs-on: ubuntu-latest
    steps:
      - name: Check for code changes
        uses: actions/checkout@v2
      - name: Enforce code coverage report
        run: <insert code coverage command>
      - name: Verify code linting and unit tests
        run: <insert linting and unit test command>
      - name: Complete job
        run: <insert completion command>