


name: branch-protection
on:
  push:
    branches:
      - main
jobs:
  enforce-branch-rules:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      - name: Check for code changes
        run: |
          git diff-tree --no-commit-id --name-only -r ${{ github.sha }}
      - name: Enforce code coverage report
        run: |
          npm run coverage-report
      - name: Verify code linting and unit tests
        run: |
          npm run lint
          npm run test
      - name: Complete job
        run: |
          echo "Job completed successfully."