

name: branch-protection.yml

on:
  push:
    branches:
      - main

jobs:
  enforce-branch-rules:
    runs-on: ubuntu-latest
    steps:
      - name: Check for code changes
        run: |
          if [[ `git diff --name-only HEAD HEAD^` ]]; then
            echo "Code changes detected."
          else
            echo "No code changes detected. Skipping workflow."
            exit 0
          fi
      - name: Download code coverage report
        uses: actions/download-artifact@v2
        with:
          name: code-coverage-report
      - name: Build with Gradle
        run: |
          ./gradlew build
      - name: Run code linting
        run: |
          ./gradlew lint
      - name: Run unit tests
        run: |
          ./gradlew test
      - name: Check for successful linting and tests
        run: |
          if [[ $? -eq 0 ]]; then
            echo "Code linting and unit tests passed."
          else
            echo "Code linting or unit tests failed. Workflow failed."
            exit 1
          fi
      - name: Fail workflow if requirements