

name: branch-protection.yml

on:
  push:
    branches: [main]

jobs:
  enforce-branch-rules:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - name: Check for code changes
        run: git diff --quiet || echo "::set-output name=changes::true"
      - name: Enforce requirements
        if: steps.check.outputs.changes
        run: |
          # Check for code coverage artifact
          if [ ! -f coverage_report.txt ]; then
            echo "Code coverage report not found."
            exit 1
          fi
          # Check for successful linting and unit tests
          if [ ! -f linting_success.txt ]; then
            echo "Linting and unit tests failed."
            exit 1
          fi
      - name: Fail workflow if requirements not met
        if: steps.check.outputs.changes && ( ${{ failure() }} || ${{ cancelled() }} )
        run: echo "One or more requirements were not met. Push to main branch prevented."