.

YAML:
# This is a basic workflow to help you get started with GitHub Actions

name: CI/CD Workflow # Name of the workflow

on:
  push: # Trigger the workflow on push events
    branches: [ main ] # Only run this workflow on the main branch
  pull_request: # Trigger the workflow on pull request events
    branches: [ main ] # Only run this workflow on the main branch

jobs:
  build:
    runs-on: ubuntu-latest # The type of runner that the job will run on

    steps:
      - uses: actions/checkout@v2 # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Run Tests # Name of the step
        run: npm test # Command to run to execute tests
      - name: Build and Deploy # Name of the step
        run: npm run build && npm run deploy # Command to build and deploy the project
  deploy:
    needs: build # Specifies that this job is dependent on the 'build' job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to Production # Name of