


name: branch-protection.yml

on:
  push:
    branches: [main]

jobs:
  enforce-branch-rules:
    runs-on: ubuntu-latest
    steps:
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Check for code changes
        uses: actions/github-script@v5
        with:
          script: |
            const commits = await github.repos.listCommits({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.sha
            })
            if (commits.data.length > 0) {
              // enforce code coverage report
              // verify code linting and unit tests
              // complete job
            } else {
              // do not run any jobs
            }