

---
name: branch-protection.yml

on:
  push:
    branches:
      - main

jobs:
  enforce-branch-rules:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
    - name: check for code changes
      if: github.event.action == 'push'
      run: |
        if [ -z "$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }})" ]; then
            echo "No code changes detected.";
        else
            echo "Code changes detected.";
        fi
    - name: enforce code coverage report
      if: github.event.action == 'push'
      run: |
        npm run coverage
    - name: verify code linting and unit tests
      if: github.event.action == 'push'
      run: |
        npm run lint
        npm run test
    - name: complete job
      if: github.event.action == 'push'
      run: |
        echo "Job completed successfully."