


name: branch-protection.yml

on:
  push:
    branches: 
      - main

jobs:
  enforce-branch-rules:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [20]
    if: github.event_name == 'push' && contains(github.event.head_commit.modified, 'code')
    steps:
      - name: setup job
        run: npm install
      - name: check for code changes
        run: git diff --name-only HEAD~1 HEAD
      - name: enforce code coverage report
        run: npm run test-coverage
      - name: verify code linting and unit tests
        run: npm run lint && npm test
      - name: complete job
        run: npm run build