 branch-ci-cd-pipeline.yml

name: branch-ci-cd-pipeline.yml

on:
  push:
    branches: [main]

jobs:
  enforce-branch-rules:
    runs-on: macOS-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Check for code changes
        run: git diff --exit-code
        continue-on-error: true
      - name: Check code coverage report
        uses: actions/download-artifact@v2
        with:
          name: code-coverage-report
          path: code-coverage-report
      - name: Verify code linting and unit tests
        uses: actions/download-artifact@v2
        with:
          name: linting-and-unit-tests
          path: linting-and-unit-tests
      - name: Fail workflow if requirements not met
        run: exit 1