

name: branch-protection.yml

on: 
  push:
    branches: 
      - main

jobs:
  enforce-branch-rules:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      - uses: actions/checkout@v2
        if: contains(github.event.head_commit.modified, 'code changes')
        name: check code changes
      - name: enforce rules
        run: |
          # insert suitable enforce rules here
      - name: set up job
        run: |
          # insert code coverage report setup here
      - name: verify code linting and unit tests
        run: |
          # insert code linting and unit tests here
      - name: complete job
        run: |
          # insert code to complete job here