

YAML:
name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    name: Setup Job
    runs-on: ubuntu-latest
    steps:
      - name: Check for Code Changes
        uses: actions/checkout@v2
      - name: Enforce Code Coverage Report
        run: npm run coverage
      - name: Verify Code Linting and Unit Tests
        run: npm run lint && npm run test
      - name: Complete Job
        run: npm run build && npm run deploy