

name: deploy-and-notify
on:
  pull_request:
    branches:
      - develop
jobs:
  build:
    runs-on: centos-8
    steps:
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
          default: true
      - name: Install dependencies
        run: yarn install
      - name: Build project
        run: ./build.sh
      - name: Deploy to testing environment
        if: success()
        run: deploy.sh
      - name: Notify Microsoft Teams
        if: success()
        uses: microsoft/teams-notification@v1
        with:
          message: Deployment successful