

name: branch-protection.yml

on:
  push:
    branches: 
      - main

jobs:
  enforce-branch-rules:
    runs-on: ubuntu-latest
    steps:
      - name: Check for Code Changes
        if: github.event_name == 'push'
        run: |
          git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | grep -E '.*\.(js|ts|go|py)$'
      - name: Set Up Job
        if: steps.check-code-changes.outputs.code-changes == 'true'
        run: echo "Setting up job..."
      - name: Enforce Code Coverage Report
        if: steps.check-code-changes.outputs.code-changes == 'true'
        run: echo "Enforcing code coverage report..."
      - name: Verify Code Linting and Unit Tests
        if: steps.check-code-changes.outputs.code-changes == 'true'
        run: echo "Verifying code linting and unit tests..."
      - name: Complete Job
        if: steps.check-code-changes.outputs.code-changes == 'true'
        run: echo "Job completed successfully."