

name: branch-protection.yml

on:
  push:
    branches:
      - main

jobs:
  enforce-branch-rules:
    runs-on: windows-latest
    
    strategy:
      matrix:
        node-version: [20.x]
        
    steps:
      - name: Check for code changes
        uses: actions/checkout@v2
        
      - name: Enforce code coverage report
        if: ${{ github.event_name == 'push' && contains(github.event.head_commit.modified, 'code') }}
        run: enforce code coverage report
        
      - name: Verify code linting and unit tests
        if: ${{ github.event_name == 'push' && contains(github.event.head_commit.modified, 'code') }}
        run: verify code linting and unit tests
        
      - name: Complete job
        run: complete job