

name: branch-protection.yml

on:
  push:
    branches:
      - main

jobs:
  enforce-branch-rules:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Check for code changes
        uses: actions/checkout@v2
      - name: Set up job
        run: npm install
      - name: Enforce code coverage report
        run: npm run coverage
      - name: Verify code linting and unit tests
        run: npm run lint && npm test
      - name: Complete job
        run: npm run build && npm run deploy