
name: ci-cd.yml
on:
  push:
    branches: [main]
jobs:
  enforce-branch-rules:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: check for code changes
        run: |
          if git diff-tree --no-commit-id --name-only -r ${{github.sha}}; then
            echo "Code changes detected"
          else
            echo "No code changes detected"
            exit 1
        shell: bash
      - name: check for code coverage report
        uses: actions/download-artifact@v2
        with:
          name: code-coverage-report
          path: coverage-report
      - name: check for code linting and unit tests
        uses: actions/download-artifact@v2
        with:
          name: linting-and-unit-tests
          path: linting-and-unit-tests
      - name: fail workflow if requirements are not met
        run: exit 1
        if: ${{failure()}}
        shell: bash