

name: branch-protection.yml
on:
  push:
    branches: [main]
jobs:
  enforce-branch-rules:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      - name: Check for Code Changes
        if: ${{ github.event_name == 'push' && github.event.ref == 'main' }}
        uses: actions/checkout@v2
      - name: Enforce Code Coverage Report
        run: npm run code-coverage
      - name: Verify Code Linting and Unit Tests
        run: npm run lint && npm run test
      - name: Complete Job
        run: echo "Job completed successfully."