

name: branch-protection.yml
on:
  push:
    branches: [main]

jobs:
  enforce-branch-rules:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [20]

    steps:
      - name: Check for code changes
        run: git diff --quiet || echo "Changes detected"

      - name: Enforce code coverage report
        if: ${{ steps.code_changes.outputs.code_changes == 'true' }}
        run: npm run coverage-report

      - name: Verify code linting and unit tests
        if: ${{ steps.code_changes.outputs.code_changes == 'true' }}
        run: npm run lint && npm run unit-tests

      - name: Complete job
        if: ${{ steps.code_changes.outputs.code_changes == 'true' }}
        run: echo "Job completed successfully"