

name: branch-protection.yml

on:
  push:
    branches: [main]

jobs:
  enforce-branch-rules:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      - name: Check for code changes
        if: ${{ github.event_name == 'push' && contains(github.event.head_commit.modified, 'code') }}
        run: echo "Code changes detected."
      - name: Enforce code coverage report
        if: ${{ github.event_name == 'push' && contains(github.event.head_commit.modified, 'code') }}
        run: npm run coverage
      - name: Verify code linting and unit tests
        if: ${{ github.event_name == 'push' && contains(github.event.head_commit.modified, 'code') }}
        run: npm run lint && npm run test
      - name: Complete job
        run: echo "Job completed successfully."