
name: ci-cd.yml

on:
  push:
    branches: [main]

jobs:
  enforce-branch-rules:
    runs-on: macOS-latest
    steps:
      - name: Check for code changes
        run: |
          git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | grep "\.py$"
        id: code_changes
      - name: Get code coverage report
        uses: actions/download-artifact@v2
        with:
          name: code-coverage
          path: code-coverage
        if: steps.code_changes.outputs.code_changes == true
      - name: Check code linting and unit tests
        uses: actions/download-artifact@v2
        with:
          name: lint-test-report
          path: lint-test-report
        if: steps.code_changes.outputs.code_changes == true
      - name: Fail if requirements not met
        run: exit 1
        if: steps.code_changes.outputs.code_changes == true && (steps.code_coverage.outputs.code_coverage == 'not-found' || steps.lint_test_report.outputs.lint_test_report == 'not-found')