
name: branch-protection.yml

on:
  push:
    branches: [main]

jobs:
  enforce-branch-rules:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      - name: Check for code changes
        if: github.event_name == 'push'
        id: code_changes
        run: |
          if git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | grep -q '.js'; then
            echo "Code changes detected."
            echo "::set-output name=changes::true"
          else
            echo "No code changes detected."
            echo "::set-output name=changes::false"
      - name: Enforce code coverage report
        if: steps.code_changes.outputs.changes == 'true'
        run: echo "Enforcing code coverage report."
      - name: Verify code linting and unit tests
        if: steps.code_changes.outputs.changes == 'true'
        run: echo "Verifying code linting and unit tests."
      - name: Complete job
        if: steps.code_changes.outputs.changes == 'true'
        run: echo "Job completed successfully."