


name: branch-protection.yml

on:
  push:
    branches: main

jobs:
  enforce-branch-rules:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      - name: Check for code changes
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Enforce code coverage report
        run: |
          if [ -n "$GITHUB_TOKEN" ]; then
            npm install -g codecov
            npm install -g nyc
            npm install --save-dev istanbul
            npm install --save-dev coveralls
            npm install --save-dev mocha
            npm install --save-dev chai
            npm install --save-dev nyc
            nyc --reporter=lcovonly mocha
            codecov
            coveralls
          fi
      - name: Verify code linting and unit tests
        run: |
          npm install -g eslint
          npm install --save-dev eslint
          npm install --save-dev eslint-config-airbnb-base
          npm install --save-dev eslint-config-prettier
          npm install --save-dev eslint-plugin