

name: branch-protection.yml

on:
  push:
    branches:
      - main

jobs:
  enforce-branch-rules:
    runs-on: ubuntu-latest
    steps:
      - name: Check code changes
        run: git diff --name-only ${{ github.event.before }} ${{ github.event.after }}
      - name: Ensure code coverage report is available
        uses: actions/download-artifact@v2
        with:
          name: code-coverage-report
          path: coverage-report
      - name: Verify code linting and unit tests
        uses: actions/download-artifact@v2
        with:
          name: linting-and-unit-tests
          path: linting-and-unit-tests
      - name: Fail workflow if requirements are not met
        run: |
          if [ -z "$COVERAGE_REPORT_PATH" ] || [ -z "$LINTING_AND_UNIT_TESTS_PATH" ]; then
            echo "One or more requirements were not met. Push to main is not allowed.";
            exit 1;
          fi