
name: branch-protection.yml

on:
  push:
    branches:
      - main

jobs:
  enforce-branch-rules:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Check for code changes
        run: |
          if [[ $(git diff --name-only ${{ github.base_ref }}..${{ github.head_ref }}) ]]; then
            touch code-changes.txt
          else
            touch no-code-changes.txt
          fi
      - name: Check code coverage report
        if: success()
        uses: actions/download-artifact@v2
        with:
          name: code-coverage-report
          path: coverage-report
      - name: Build with Java Maven
        if: success()
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Java Gradle
        if: success()
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Run code linting and unit tests
        if: success()
        uses: actions