

name: release-pipeline.yml

on: 
  push:
    branches: [main]

jobs:
  enforce-branch-rules:
    runs-on: macOS-latest
    steps:
      - name: Check for code changes
        uses: actions/github-script@v3
        with:
          script: |
            const changedFiles = await github.event.commits[0].added.concat(github.event.commits[0].modified);
            if (changedFiles.length === 0) {
              core.setFailed('No code changes were included in the push to main.');
            }

      - name: Check for code coverage report
        uses: actions/download-artifact@v2
        with:
          name: code-coverage
          path: coverage-report

      - name: Verify code linting and unit tests
        uses: actions/download-artifact@v2
        with:
          name: linting-and-unit-tests
          path: linting-and-unit-tests

      - name: Fail if requirements not met
        run: |
          if [ -d "coverage-report" ] && [ -d "linting-and-unit-tests" ]; then
            echo "All requirements met.";
          else
            echo "One or more requirements