


name: branch-protection.yml

on:
  push:
    branches:
      - main

jobs:
  enforce-branch-rules:
    runs-on: ubuntu-latest
    steps:
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Check for code changes
        run: |
          if [ $(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | wc -l) -ne 0 ]; then
            # enforce code coverage report
            # verify code linting and unit tests
          fi
      - name: Complete job
        run: |
          # take your own requirements and generate to run jobs sucessfully