

name: branch-protection.yml
on:
  push:
    branches:
      - main
jobs:
  enforce-branch-rules:
    runs-on: ubuntu-latest
    name: enforce-branch-rules
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: check for code changes
        run: git diff-tree --no-commit-id --name-only -r ${{ github.sha }}
      - name: enforce code coverage report
        if: ${{ steps.check-code-changes.outputs.code-changed == 'true' }}
        run: npm run coverage
      - name: verify code linting and unit tests
        if: ${{ steps.check-code-changes.outputs.code-changed == 'true' }}
        run: npm run lint && npm run test
      - name: complete job
        if: ${{ steps.check-code-changes.outputs.code-changed == 'true' }}
        run: echo "Job completed successfully."
      - name: set up job
        run: setup-job
      - name: check for code changes
        run: git diff-tree --no-commit-id --name