

name: branch-protection.yml

on:
  push:
    branches: [main]

jobs:
  enforce-branch-rules:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && contains(github.event.head_commit.modified, '.py')
    steps:
      - name: set up job
        run: echo "Setting up job"
      - name: check for code changes
        run: git diff --exit-code --quiet HEAD^ HEAD
      - name: enforce code coverage report
        run: pytest --cov=./
      - name: verify code linting and unit tests
        run: flake8 && pytest
      - name: complete job
        run: echo "Job completed successfully"
