


name: branch-protection.yml
on:
  push:
    branches:
      - main
jobs:
  enforce-branch-rules:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ matrix.node-version }}
      - name: Setup Maven
        uses: actions/setup-java@v1
        with:
          java-version: '11.x'
      - name: Check for code changes
        run: git diff --exit-code
      - name: Enforce code coverage report
        run: mvn jacoco:report
      - name: Verify code linting and unit tests
        run: npm test
      - name: Complete job
        run: echo "Job complete."
