
# Name: branch-protection.yml

# This workflow runs on push events to the main branch.
on:
  push:
    branches:
      - main

# Define a single job named enforce-branch-rules.
jobs:
  enforce-branch-rules:
    # Run on windows-latest.
    runs-on: windows-latest
    # Run on Node.js 20.
    strategy:
      matrix:
        node-version: [20]
    # Check if the pushed commit includes code changes.
    steps:
      - name: Check for code changes
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Enforce Code Coverage Report
        run: npm run coverage
      - name: Verify Code Linting and Unit Tests
        run: npm run lint && npm run test
      - name: Complete Job
        run: echo "Job Completed Successfully"