
---
# Name of YAML file
name: branch-protection

# Workflow triggers
on:
  push:
    branches:
      - main

# Define a single job
jobs:
  enforce-branch-rules:
    # Run on windows-latest
    runs-on: windows-latest
    # Run on Node.js 20
    strategy:
      matrix:
        node-version: [20.x]
    
    # Define steps for the job
    steps:
      # Check for code changes
      - name: Check for code changes
        if: github.event_name == 'push'
        run: |
          if git diff --name-only ${{ github.base_ref }}..${{ github.head_ref }} | grep -qvE '(.md)|(.png)|(.txt)|(.yml)'
          then
            echo 'Code changes detected.'
          else
            echo 'No code changes detected. Skipping job.'
            exit 1
          fi
      
      # Set up job
      - name: Set up job
        if: ${{ always() }}
        run: |
          # Install maven and java
          sudo apt-get install maven
          sudo apt-get install default-jre
          # Clone repository
          git clone