

name: branch-protection.yml

on:
  push:
    branches: [main]

jobs:
  enforce-branch-rules:
    runs-on: windows-latest
    steps:
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 20
      - name: Check for code changes
        if: github.event_name == 'push'
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '.*\.\(js\|ts\)$'; then
            echo "Changes found, enforcing requirements."
          else
            echo "No code changes, skipping requirements enforcement."
            exit 1
      - name: Enforce code coverage report
        run: npm run coverage
      - name: Verify code linting and unit tests
        run: npm run lint && npm run test
      - name: Complete job
        run: echo "Job completed successfully."