
mobile-ci.yml:
name: mobile-ci
on:
  pull_request:
    branches: [feature]
jobs:
  build-android:
    runs-on: macos-latest
    steps:
      - name: Checkout code from repository
        uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: '1.8'
      - name: Install Android SDK
        uses: android-actions/setup-android@v2
        with:
          sdk-platform: 'platforms;android-29'
      - name: Install Gradle
        run: sudo ./gradlew wrapper --gradle-version=6.3
      - name: Build Android app
        run: ./gradlew assembleDebug
      - name: Archive APK file
        uses: actions/upload-artifact@v2
        with:
          name: APK
          path: app/build/outputs/apk/debug/app-debug.apk
  build-ios:
    runs-on: macos-latest
    steps:
      - name: Checkout code from repository
        uses: actions/checkout@v2
      - name: Install Xcode
        uses