

name: branch-protection.yml

on:
  push:
    branches: 
      - main

jobs: 
  enforce-branch-rules:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.modified, '.github/')"
    steps:
      - name: setup job
        run: |
          # insert setup commands here
      - name: check for code changes
        run: |
          # insert code change check commands here
      - name: enforce code coverage report
        run: |
          # insert code coverage commands here
      - name: verify code linting and unit tests
        run: |
          # insert linting and unit test commands here
      - name: complete job
        run: |
          # insert completion commands here