


name: branch-protection.yml

on:
  push:
    branches:
      - main

jobs:
  enforce-branch-rules:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Check for code changes
        id: code-changes
        run: git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -E '\\.(js|jsx|ts|tsx)$'
      - name: Set up job
        if: ${{ steps.code-changes.outputs.code-changes != '' }}
        run: |
          npm i -g npm@latest
          npm i -g codecov
          npm install
      - name: Enforce code coverage report
        if: ${{ steps.code-changes.outputs.code-changes != '' }}
        run: npm run coverage
      - name: Verify code linting and unit tests
        if: ${{ steps.code-changes.outputs.code-changes != '' }}
        run: npm run lint && npm test
      - name: Complete job
        if: ${{ steps.code-changes.outputs.code-changes != '' }}
        run: echo "