


name: branch-protection.yml

on:
  push:
    branches:
      - main

jobs:
  enforce-branch-rules:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: check for code changes
        if: github.event_name == 'push'
        run: |
          git diff --name-only ${{ github.event.before }}...${{ github.event.after }} > files_changed.txt
          if [[ -s files_changed.txt ]]; then
            echo "Code changes detected."
          else
            echo "No code changes detected. Skipping job."
            exit 1
      - name: setup job
        run: npm install
      - name: enforce code coverage report
        run: npm run coverage
      - name: verify code linting and unit tests
        run: npm test
      - name: complete job
        run: echo "Job completed successfully."