

name: multi-stage-deploy.yml

on:
  push:
    branches:
      - production

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
        
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm install
      - name: Build Application
        run: npm run build
        
  stage:
    runs-on: staging-environment
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Deploy Application
        run: npm run deploy
      - name: Configure Environment
        run: npm run configure
        
  production-deploy:
    runs-on: production-environment
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Deploy Application
        run: npm run deploy
      - name: Configure Secrets
        run: npm run configure-secrets