

name: branch-protection.yml
on:
  push:
    branches: 
      - main
jobs: 
  enforce-branch-rules:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [20]
    steps: 
      - name: Check for code changes
        run: git diff --quiet || CHANGED=true
      - name: Enforce code coverage report
        if: env.CHANGED == 'true'
        run: npm test --coverage
      - name: Verify code linting and unit tests
        if: env.CHANGED == 'true'
        run: npm run lint && npm run unit-test
      - name: Complete job
        if: env.CHANGED == 'true'
        run: echo "Job complete"