

name: branch-protection.yml
on:
  push:
    branches:
      - main
jobs:
  enforce-branch-rules:
    runs-on: ubuntu-latest
    steps:
      - name: Check for code changes
        run: git diff --quiet HEAD^ HEAD
        id: code-changes
      - name: Get coverage report artifact
        uses: actions/download-artifact@v2
        if: ${{ steps.code-changes.outputs.code-changed == 'true' }}
        with:
          name: coverage-report
      - name: Build with Maven or Gradle
        uses: actions/setup-java@v2
        with:
          java-version: '11'
        if: ${{ steps.code-changes.outputs.code-changed == 'true' }}
      - name: Build job on docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
      - name: Linting and unit tests
        run: |
          # Commands for linting and unit tests
        if: ${{ steps.code-changes.outputs.code-changed == 'true' }}
      - name: Fail if requirements not met
        run: exit 1