


name: deploy-and-notify

on:
  pull_request:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: centos-8
    steps:
      - name: Install Node.js version 14
        uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/
      - name: Set default Node.js version
        run: npm install -g n && n 14
      - name: Install project dependencies
        run: yarn install
      - name: Build project
        run: ./build.sh
      - name: Deploy to testing environment
        run: ./deploy.sh
        if: success()
      - name: Notify Microsoft Teams
        uses: microsoft/teams-notification@v1
        with:
          message: Deployment successful