

name: branch-protection.yml

on:
  push:
    branches: [main]

jobs:
  enforce-branch-rules:
    runs-on: ubuntu-latest
    steps:
      - name: Check for code changes
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            if (github.context.payload.commits.length > 0) {
              console.log('Code changes detected.');
            } else {
              console.log('No code changes detected. Skipping workflow.');
              process.exit(78);
            }
      - name: Setup Gradle
        if: ${{ contains(github.event.head_commit.modified, 'java') }}
        run: sudo apt-get install gradle
      - name: Run Gradle build
        if: ${{ contains(github.event.head_commit.modified, 'java') }}
        run: gradle build
      - name: Upload code coverage report
        uses: actions/upload-artifact@v2
        if: ${{ contains(github.event.head_commit.modified, 'java') }}
        with:
          name: code-coverage-report
          path: ./build/reports/coverage/index.html
      - name: Run code