

name: branch-protection.yml
on:
  push:
    branches: [main]
jobs:
  enforce-branch-rules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Node.js 16
        uses: actions/setup-node@v2-legacy
        with:
          node-version: 16
      - name: Check for code changes
        run: git diff --name-only HEAD ${{ github.event.before }}
        id: check_changes
      - name: Enforce code coverage report
        if: steps.check_changes.outputs.code_changed == 'true'
        run: npm run coverage
      - name: Verify code linting and unit tests
        if: steps.check_changes.outputs.code_changed == 'true'
        run: npm run lint && npm run test
      - name: Complete job
        if: steps.check_changes.outputs.code_changed == 'true'
        run: echo "Job completed successfully."