

name: branch-protection.yml
on:
  push:
    branches: [main]
    
jobs:
  enforce-branch-rules:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [20]
    
    steps:
      - name: Check for code changes
        run: git diff --name-only ${{ github.sha }} ${{ github.sha }}^
        id: changed_files
        
      - name: Enforce code coverage report
        if: ${{ steps.changed_files.outputs.contains('*.js') }}
        run: npm run coverage
        
      - name: Verify code linting and unit tests
        if: ${{ steps.changed_files.outputs.contains('*.js') }}
        run: npm run lint && npm run test
        
      - name: Complete job
        if: ${{ steps.changed_files.outputs.contains('*.js') }}
        run: echo "Job completed successfully."