
      - Name: deploy
        - Runs on: ubuntu-latest
        - Needs: build
        - Steps:
            - Checkout the repository
            - Set up Node.js version 14
            - Install dependencies using npm
            - Build and package the application
            - Deploy the application

---
name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Node.js version 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Node.js version 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      -