
name: branch-protection.yml

on:
  push:
    branches: [main]

jobs:
  enforce-branch-rules:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Check for code changes
        run: |
          if [ -n "$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }})" ]; then
            echo "Code changes detected."
          else
            echo "No code changes detected."
            exit 1
          fi
      - name: Enforce code coverage report
        run: |
          npm install
          npm run coverage
      - name: Verify code linting and unit tests
        run: |
          npm install
          npm run lint
          npm test
      - name: Complete job
        run: |
          echo "Job completed successfully."