


name: branch-protection.yml

on: 
  push:
    branches: 
      - main

jobs: 
  enforce-branch-rules:
    runs-on: ubuntu-latest
    steps:
      - name: Install Node.js 16 
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Check for code changes
        if: github.event_name == 'push' && github.event.head_commit.added.length + github.event.head_commit.modified.length + github.event.head_commit.removed.length > 0
        run: echo "Code changes detected."
      - name: Enforce code coverage report
        run: npm run coverage
      - name: Verify code linting and unit tests
        run: npm run lint && npm test
      - name: Complete job
        run: echo "Job completed successfully."