

branch-protection.yaml:

name: branch-protection

on:
  push:
    branches: 
      - main

jobs:
  enforce-branch-rules:
    runs-on: ubuntu-latest
    steps:
      - name: Check for code changes
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Check code coverage report
        uses: actions/download-artifact@v2
        with:
          name: code-coverage-report
          path: code-coverage-report
      - name: Verify code linting and unit tests
        uses: actions/download-artifact@v2
        with:
          name: linting-and-unit-tests
          path: linting-and-unit-tests
      - name: Enforce requirements
        if: ${{ steps.enforce-branch-rules.outputs.code-coverage-report == 'success' && steps.enforce-branch-rules.outputs.linting-and-unit-tests == 'success' }}
        run: echo "All requirements met."
      - name: Fail workflow if requirements not met
        if: ${{ steps.enforce-branch-rules.outputs.code-coverage-report != 'success' || steps.enforce-branch-rules.outputs