

name: ci-cd.yml

on:
  push:
    branches: [main]

jobs:
  enforce-branch-rules:
    runs-on: macos-latest
    if: github.event_name == 'push'
    steps:
      - name: Check for code changes
        run: |
          if [ -z "$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }})" ]; then
            echo "No code changes detected. Skipping enforcement."
            exit 1
          fi
      - name: Enforce code coverage report
        uses: actions/upload-artifact@v2
        with:
          path: code-coverage-report
      - name: Verify code linting and unit tests
        uses: actions/upload-artifact@v2
        with:
          path: code-linting-unit-tests
      - name: Fail if requirements not met
        run: |
          if [ -z "$(ls code-coverage-report)" ] || [ -z "$(ls code-linting-unit-tests)" ]; then
            echo "Code coverage report or linting/unit tests not found. Push to main branch not allowed."
            exit 1
          fi