

name: branch-protection

on:
  push:
    branches:
      - main

jobs:
  enforce-branch-rules:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && contains(github.event.head_commit.modified, 'code') }}
    steps:
      - name: setup job
        run: |
          # insert code for setting up job here
      - name: check for code changes
        run: |
          # insert code for checking code changes here
      - name: enforce code coverage report
        run: |
          # insert code for enforcing code coverage report here
      - name: verify code linting and unit tests
        run: |
          # insert code for verifying code linting and unit tests here
      - name: complete job
        run: |
          # insert code for completing job here