


name: branch-protection

on:
  push:
    branches: [main]

jobs:
  enforce-branch-rules:
    runs-on: windows-latest
    steps:
      - name: Use Node.js 20
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Check for code changes
        run: |
          git fetch origin main
          changes=$(git diff --name-only origin/main)
          if [ -n "$changes" ]; then
            echo "Code changes detected."
          else
            echo "No code changes detected."
            exit 0
          fi
      - name: Enforce code coverage report
        run: npm run coverage
      - name: Verify code linting and unit tests
        run: npm test
      - name: Complete job
        run: echo "Branch rules successfully enforced."