

name: branch-protection.yml

on:
  push:
    branches: 
      - main

jobs:
  enforce-branch-rules:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.modified, '.md')"
    steps:
      - name: Check Code Changes
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Ensure Code Coverage Report
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: <path_to_report>
      - name: Build with Gradle
        run: gradle build
      - name: Check Linting and Unit Tests
        run: gradle lint test
        continue-on-error: true
      - name: Fail Workflow if Requirements Not Met
        run: exit 1