

name: branch-protection.yml

on: 
  push:
    branches:
      - main

jobs: 
  enforce-branch-rules:
    runs-on: windows-latest
    strategy:
      matrix:
        node_version: [20]
    steps:
      - name: Check for code changes
        if: github.event_name == 'push'
        run: |
          git diff --quiet || echo "Code changes detected"
      - name: Enforce code coverage report
        if: github.event_name == 'push'
        run: |
          npm run coverage
      - name: Verify code linting and unit tests
        if: github.event_name == 'push'
        run: |
          npm run lint
          npm run test
      - name: Complete job
        if: github.event_name == 'push'
        run: |
          echo "Job completed successfully"