

name: deploy-to-staging-v2

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: macOS-latest
    steps:
      - name: Install Node.js version 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Set as default
        run: npm config set prefix '~/.npm-global'
      - name: Install project dependencies
        run: yarn install
      - name: Build project
        run: ./build-v2.sh
      - name: Deploy to staging
        run: ./deploy-to-staging.sh
      - name: Discord notification
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
          message: "Deployment to staging successful."