

name: branch-protection.yml
on:
  push:
    branches:
      - main
jobs:
  enforce-branch-rules:
    runs-on: ubuntu-latest
    steps:
      - name: Check for code changes
        if: github.event.commits[0].added != '' || github.event.commits[0].modified != '' || github.event.commits[0].removed != ''
        run: |
          # set up job
          # check for code changes
          # enforce code coverage report
          # verify code linting and unit tests
          # complete job
      - name: Take your own requirements
        if: github.event.commits[0].added == '' && github.event.commits[0].modified == '' && github.event.commits[0].removed == ''
        run: |
          # set up job
          # run other jobs as needed