

name: deploy-notify.yml

on:
  push:
    branches: [main]

jobs:
  enforce-branch-rules:
    runs-on: centos-8
    steps:
      - name: Check for code changes
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Enforce code coverage report
        if: ${{ steps.check_code_changes.outputs.code_changes == 'true' }}
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: <path to code coverage report>
      - name: Check for successful code linting and unit tests
        if: ${{ steps.check_code_changes.outputs.code_changes == 'true' }}
        uses: actions/upload-artifact@v2
        with:
          name: code-linting-and-unit-tests
          path: <path to code linting and unit test results>
      - name: Fail if requirements are not met
        if: ${{ steps.check_code_changes.outputs.code_changes == 'true' }}
        run: exit 1