
                - If all requirements are met, allow the push to main


name: branch-protection
on:
  push:
    branches: [main]
jobs:
  enforce-branch-rules:
    runs-on: ubuntu-latest
    steps:
      - name: Check if pushed commit includes code changes
        run: echo "Checking for code changes"
      - name: Ensure code coverage report as artifact
        run: echo "Generating code coverage report"
        if: always()
      - name: Verify code linting and unit tests
        run: echo "Running linting and unit tests"
        if: always()
      - name: Fail workflow if requirements not met
        run: echo "Requirements not met, failing workflow"
        if: ${{ failure() }}
      - name: Allow push to main if requirements met
        run: echo "Requirements met, allowing push"
        if: ${{ success() }}