

name: branch-protection.yml

on:
  push:
    branches: [main]

jobs:
  enforce-branch-rules:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: check for code changes
        uses: actions/checkout@v2
      - name: enforce requirements
        if: ${{ github.event.commits }}
        run: |
          # insert code for setting up job
          # insert code for checking code changes
          # insert code for enforcing code coverage report
          # insert code for verifying code linting and unit tests
          # insert code for completing job